name: Deploy

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    docker_image_build:
        name: Docker image build
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Convert repository name to lowercase
              id: repo-name
              run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

            - name: Build and push docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ env.REPO_LC }}:${{ github.sha }},
                      ghcr.io/${{ env.REPO_LC }}:${{ github.ref_name }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
